modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="legacy_heroes"
version="0.0.2"
displayName="Legacy Heroes"
displayURL="https://discord.gg/PG45nNWssF"
credits="OG20122012 & Westankrang"
authors="Maketendo"
description="Adds Quirks and Support Items from the series My Hero Academia!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.legacy_heroes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.legacy_heroes]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration